version: '2'
services:
  mongo:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./data:/data/db
    command: mongod --directoryperdb
    env_file:
      - ../.env

  jsoauth2:
    depends_on:
      - mongo
    image: twhtanghk/jsoauth2
    ports:
      - 3000
    env_file:
      - ./.env
      - ../.env

networks:
  default:
    external:
      name: net_default 
