version: '3'
services:
  opencpn:
    image: twhtanghk/opencpn
    devices:
      - /dev/snd
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root
    network_mode: host
    environment:
      - DISPLAY
    env_file:
      - ../.env
