version: '2'
services:
  consul:
    image: consul
    networks:
      default:
        ipv4_address: 192.168.65.32
    command: agent -config-dir /consul/config -server -bootstrap -ui
    ports:
      - 53/tcp
      - 53/udp
      - 8500
    volumes:
      - ${COMPOSEROOT}/consul/consul.json:/consul/config/consul.json
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    env_file:
      - ../.env

  registrator:
    depends_on:
      - consul
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://192.168.65.32:8500
    env_file:
      - ../.env

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.65.0/24
