version: '3'
services:
  freecad:
    image: twhtanghk/freecad:0.20.2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root
    environment:
      - DISPLAY
      - QTWEBENGINE_DISABLE_SANDBOX=1
    command: top -b -d 1000
