version: '3'
services:
  freecad:
    image: twhtanghk/freecad
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root
    environment:
      - DISPLAY
