version: '2'
services:
  xrdp:
    image: twhtanghk/docker.xrdp
    network_mode: host
    ports:
      - 3389
    volumes:
      - ./xrdp:/home/user
    env_file:
      - ../.env
    networks:
      - stock

networks:
  stock:
    external: true
    enable_ipv6: false
