services:
  binance:
    image: twhtanghk/binance:reconnect
    environment:
      - LEVEL=debug
      - BINANCE_API_KEY
      - BINANCE_RSA_KEY
    env_file:
      - ../.env
    command: "npm run mean -- --order '{\"nShare\": 10}'"
