services:
  binance:
    image: twhtanghk/binance
    volumes:
      - ./binance-private-key.pem:/usr/src/app/binance-private-key.pem
    environment:
      - LEVEL=debug
      - BINANCE_API_KEY
      - BINANCE_RSA_KEY
    env_file:
      - ../.env
    command: tail -f /dev/null
