version: '2'
services:
  nativescript:
    image: twhtanghk/nativescript
    privileged: true
    volumes:
      - /dev:/dev
      - ./data:/root/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
    env_file:
      - ../.env
    stdin_open: true
    tty: true
