services:
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www
      - ./ssl/nginx.key:/etc/ssl/private/nginx.key
      - ./ssl/nginx.pem:/etc/ssl/certs/nginx.pem
    env_file: 
      - ../.env
