version: '2'
services:
  smtp:
    image: namshi/smtp
    ports:
      - $ip:25:25
    volumes:
      - ./data/mail:/var/mail
      - ./data/aliases:/etc/aliases
    dns:
      - 8.8.8.8
    env_file: 
      - ../.env
      - ./.env
    restart: unless-stopped
