version: '2'
services:
  echo:
    image: solsson/http-echo
    ports: 
      - 80

  proxy:
    image: twhtanghk/sails_proxy
    ports:
      - 1337
    volumes:
      - ./data:/usr/src/app/data
      - ./ssl:/usr/src/app/config/env/ssl
    env_file: 
      - ../.env
      - ./.env

networks:
  default:
    external:
      name: net_default
