version: '2'
services:
  mongo:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./data:/data/db
    command: mongod --directoryperdb

  echo:
    image: solsson/http-echo
    ports: 
      - 80

  sails_proxy:
    image: twhtanghk/sails_proxy
    ports:
      - 1337
    volumes:
      - ./production.coffee:/usr/src/app/config/env/production.coffee
    env_file: 
      - ../.env
