version: '2'
services:
  candle:
    image: twhtanghk/candle
    devices:
      - /dev/ttyACM0
      - /dev/dri
    volumes:
      - ../src:/root
      - ./settings.ini:/usr/local/bin/settings.ini
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
    environment:
      - DISPLAY
    env_file:
      - ../.env
