version: '2'
services:
  candle:
    image: twhtanghk/candle
    devices:
      - /dev/dri
    volumes:
      - /dev/ttyS0:/dev/ttyS0
      - ../src:/root
      - ./settings.ini:/usr/local/bin/settings.ini
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
    environment:
      - DISPLAY
    env_file:
      - ../.env
# socat pty,raw,link=/dev/ttyS0 tcp:192.168.0.102:23
