version: '2'
services:
  blender:
    image: ikester/blender
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root
    entrypoint: /usr/local/blender/blender
    environment:
      - DISPLAY
