version: '2'
services:
  pycam:
    image: twhtanghk/pycam
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root/src
    environment:
      - DISPLAY
