version: '2'
services:
  inkscape:
    image: twhtanghk/inkscape
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /usr/share/fonts:/usr/share/fonts
      - ../src:/root
    environment:
      - DISPLAY
