version: '2'
services:
  vncproxy:
    image: twhtanghk/vncproxy
    ports:
      - 1337
    env_file: 
      - ../.env
    volumes:
      - ./production.coffee:/usr/src/app/config/env/production.coffee
